### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by sillasgonzaga** [litdevelopers/tinder#23]
```
sillas@sillasLaptop ~/Downloads/tinder/tinder $ sudo npm start

> react-boilerplate@3.0.0 start /home/sillas/Downloads/tinder/tinder
> cross-env NODE_ENV=development babel-watch server

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-watch ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development babel-watch server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development babel-watch server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development babel-watch server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sillas/.npm/_logs/2017-03-18T01_12_09_328Z-debug.log

```
The log output:
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.4.1
3 info using node@v7.7.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-boilerplate@3.0.0~prestart: react-boilerplate@3.0.0
6 silly lifecycle react-boilerplate@3.0.0~prestart: no script for prestart, continuing
7 info lifecycle react-boilerplate@3.0.0~start: react-boilerplate@3.0.0
8 verbose lifecycle react-boilerplate@3.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-boilerplate@3.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/sillas/Downloads/tinder/tinder/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle react-boilerplate@3.0.0~start: CWD: /home/sillas/Downloads/tinder/tinder
11 silly lifecycle react-boilerplate@3.0.0~start: Args: [ '-c', 'cross-env NODE_ENV=development babel-watch server' ]
12 silly lifecycle react-boilerplate@3.0.0~start: Returned: code: 1  signal: null
13 info lifecycle react-boilerplate@3.0.0~start: Failed to exec start script
14 verbose stack Error: react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development babel-watch server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-boilerplate@3.0.0
16 verbose cwd /home/sillas/Downloads/tinder/tinder
17 verbose Linux 3.19.0-32-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v7.7.3
20 verbose npm  v4.4.1
21 error code ELIFECYCLE
22 error errno 1
23 error react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development babel-watch server`
23 error Exit status 1
24 error Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development babel-watch server'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the react-boilerplate package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=development babel-watch server
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs react-boilerplate
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls react-boilerplate
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by sillasgonzaga** [comment]
```
sillas@sillasLaptop ~/Downloads/tinder/tinder $ nodejs --version
v6.10.0
sillas@sillasLaptop ~/Downloads/tinder/tinder $ npm --version
4.4.1

```

**Comment by eddiewang** [comment]
what OS are you using?

**Comment by sillasgonzaga** [comment]
Linux Mint 17.3 Rosa (Ubuntu 14.04.5 LTS)

**Comment by eddiewang** [comment]
try upgrade npm and then running yarn. might also want to try removing cross-env to see if that fixes the issue.

**Comment by eddiewang** [comment]
closing bc haven't heard back.
